### ISSUE TITLE
The All() search method fails with Azure Search

### ISSUE THREAD

**Issue by Shazwazza** [SDKits/ExamineX#57]
The syntax used to generate this query is: `+*:*` which is acceptable by Lucene but not by Azure Search.

**Comment by netaddicts** [comment]
I'm not sure this is related to this issue, but we also run into issues when we're trying to perform a search in a content picker dialog with the following error message

`Failed to parse query string at line 1, column 11. See https://aka.ms/azure-search-full-query for supported syntax. Status: 400 (Bad Request) ErrorCode: InvalidRequestParameter Content: {"error":{"code":"InvalidRequestParameter","message":"Failed to parse query string at line 1, column 11. See https://aka.ms/azure-search-full-query for supported syntax.","details":[{"code":"InvalidSearchSyntax","message":"Failed to parse query string at line 1, column 11. See https://aka.ms/azure-search-full-query for supported syntax."}]}} Headers: Cache-Control: no-cache Pragma: no-cache client-request-id: 4d79b8a5-21d8-4d03-99dc-06d59fb68fe9 x-ms-client-request-id: 4d79b8a5-21d8-4d03-99dc-06d59fb68fe9 request-id: 4d79b8a5-21d8-4d03-99dc-06d59fb68fe9 elapsed-time: 357 OData-Version: 4.0 Preference-Applied: REDACTED Strict-Transport-Security: REDACTED Date: Tue, 07 Jun 2022 11:55:57 GMT Content-Type: application/json; odata.metadata=none Content-Language: REDACTED Expires: -1 Content-Length: 343`

`Azure.RequestFailedException, Azure.Core, Version=1.19.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8: Failed to parse query string at line 1, column 11. See https://aka.ms/azure-search-full-query for supported syntax. Status: 400 (Bad Request) ErrorCode: InvalidRequestParameter Content: {"error":{"code":"InvalidRequestParameter","message":"Failed to parse query string at line 1, column 11. See https://aka.ms/azure-search-full-query for supported syntax.","details":[{"code":"InvalidSearchSyntax","message":"Failed to parse query string at line 1, column 11. See https://aka.ms/azure-search-full-query for supported syntax."}]}} Headers: Cache-Control: no-cache Pragma: no-cache client-request-id: 4d79b8a5-21d8-4d03-99dc-06d59fb68fe9 x-ms-client-request-id: 4d79b8a5-21d8-4d03-99dc-06d59fb68fe9 request-id: 4d79b8a5-21d8-4d03-99dc-06d59fb68fe9 elapsed-time: 357 OData-Version: 4.0 Preference-Applied: REDACTED Strict-Transport-Security: REDACTED Date: Tue, 07 Jun 2022 11:55:57 GMT Content-Type: application/json; odata.metadata=none Content-Language: REDACTED Expires: -1 Content-Length: 343`

Stacktrace

```
at Azure.Search.Documents.SearchClient.SearchInternal[T](SearchOptions options, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Search.Documents.SearchClient.SearchInternal[T](String searchText, SearchOptions options, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Search.Documents.SearchClient.Search[T](String searchText, SearchOptions options, CancellationToken cancellationToken)
   at ExamineX.AzureSearch.AzureSearchResults.a.A()
   at ExamineX.AzureSearch.AzureSearchResults.A[A](Int32 , Int32 , String , Func`1 , Func`1 )
   at ExamineX.AzureSearch.AzureSearchResults.get_TotalItemCount()
   at Umbraco.Cms.Infrastructure.Examine.BackOfficeExamineSearcher.Search(String query, UmbracoEntityTypes entityType, Int32 pageSize, Int64 pageIndex, Int64& totalFound, String searchFrom, Boolean ignoreUserStartNodes)
   at Umbraco.Cms.Infrastructure.Search.UmbracoTreeSearcher.ExamineSearch(String query, UmbracoEntityTypes entityType, Int32 pageSize, Int64 pageIndex, Int64& totalFound, String culture, String searchFrom, Boolean ignoreUserStartNodes)
   at Umbraco.Cms.Web.BackOffice.Controllers.EntityController.ExamineSearch(String query, UmbracoEntityTypes entityType, String searchFrom, Boolean ignoreUserStartNodes)
   at Umbraco.Cms.Web.BackOffice.Controllers.EntityController.Search(String query, UmbracoEntityTypes type, String searchFrom, Nullable`1 dataTypeKey)
   at lambda_method2132(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)



```

**Comment by netaddicts** [comment]
Also tried to override log level to get some debugging info on the error, but didn't make any effect, can only see the error message as reported above (in a popup)

**Comment by Shazwazza** [comment]
Thanks @netaddicts , can you please confirm which version of ExamineX you are using ?

**Comment by netaddicts** [comment]
Of course, sorry, always forget to provide all possible info, we're using ExamineX 3.0.1/Examine 2.0.1

**Comment by Shazwazza** [comment]
Hi @netaddicts,

I've debugged this and it turns out that the query parser that ExamineX is using strips out the escaped text when using a Path query which results in the query not parsing correctly on the server side.

I'm researching a fix for this now.

**Comment by Shazwazza** [comment]
@netaddicts I've created a separate issue for this here https://github.com/SDKits/ExamineX/issues/61

I have fixed it so will publish a new release today.
