### ISSUE TITLE
ExamineX on Umbraco 10.*

### ISSUE THREAD

**Issue by hallojoe** [SDKits/ExamineX#64]
ExamineX 3.0.5 on Umbraco 9.5.2  works great. I would like to run it on Umbraco 10.0.1. 

When trying ExamineX on Umbraco 10.0.1 ExamineX will create indexes on the Azure Search Service and then fail when trying to populate them: 

    [09:53:45 ERR] Index populating failed for populator Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator
    System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.Collections.Generic.List`1<System.Object>> Examine.ValueSet.get_Values()'.
       at ExamineX.AzureSearch.ValueSetExtensions.CloneWithLock(IEnumerable`1 values)
       at ExamineX.AzureSearch.Umbraco.UmbracoContentAzureSearchIndex.Examine.IIndex.IndexItems(IEnumerable`1 )
       at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.IndexAllContent(Int32 contentParentId, Int32 pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)
       at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
       at Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes, TimeSpan delay, CancellationToken cancellationToken)
    
    [09:53:45 ERR] Index populating failed for populator Umbraco.Cms.Infrastructure.Examine.PublishedContentIndexPopulator
    System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.Collections.Generic.List`1<System.Object>> Examine.ValueSet.get_Values()'.
       at ExamineX.AzureSearch.ValueSetExtensions.CloneWithLock(IEnumerable`1 values)
       at ExamineX.AzureSearch.Umbraco.UmbracoContentAzureSearchIndex.Examine.IIndex.IndexItems(IEnumerable`1 )
       at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.IndexPublishedContent(Int32 contentParentId, Int32 pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)
       at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
       at Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes, TimeSpan delay, CancellationToken cancellationToken) 

Is a release supporting Umbraco 10.* planned?

**Comment by Shazwazza** [comment]
Hi, an ExamineX version hasn't been shipped yet that supports Umbraco 10. Will work on getting something out asap which will be version 4.0.0

**Comment by WeAreJigital** [comment]
@Shazwazza Do you have an idea on timescales?  Just trying to work out how i can do search with Azure and Umbraco 10 :D

**Comment by Shazwazza** [comment]
@hallojoe great to hear and thanks for testing. I'll get an RTM release out early next week.

**Comment by WeAreJigital** [comment]
@hallojoe did you get it running?  I had an issue when i tried it correct config and everything.  

I get this error and cannot reindex.

https://loom.com/i/ea524904625e4a37af714cb6ecc69580

    "AzureSearchServiceName": "random name Search",
    "AzureSearchServiceKey": "#correctkeyfromAzure#",
    "SiteFriendlyName": "random name",
    "EnvironmentType": "ByIndex"

**Comment by WeAreJigital** [comment]
Works for me as well.  I dont suppose you have any idea how we would use this with faceting and block list?

**Comment by Shazwazza** [comment]
For faceting you would use the AzureSearch APIs directly which are exposed via ExamineX, see https://examinex.online/azure-search-apis and you may need to setup facets at the index level which you can do most likely via the `CreatingOrUpdatingIndex` event (there's some example code at the bottom of https://examinex.online/customization for configuring custom things like scoring profiles)

**Comment by WeAreJigital** [comment]
Thanks @Shazwazza  that sounds like what i need?  Any resources for wireing this up?  The docs are quite high level :')

**Comment by Shazwazza** [comment]
Hi @WeAreJigital sorry I don't have anything on hand. Would be good to put some docs together for this though. I'll add that to the backlog.

**Comment by WeAreJigital** [comment]
@Shazwazza got it working, i can share what i did if you like :)

**Comment by Shazwazza** [comment]
@WeAreJigital  sounds wonderful!

**Comment by Shazwazza** [comment]
@WeAreJigital any chance you have time to share how you implemented faceting?

**Comment by WeAreJigital** [comment]
@Shazwazza sure thing :).  In the end it was not totally possible with Azure, we ran into a number of problems.  Now we have switched back to Lucene.

I can share the code i had got up to if you like, so you could start from there.  I am sure its possible, just very hard :')

**Comment by Shazwazza** [comment]
@WeAreJigital ok, would love to have some insight to how you went. I'll try to find some time to get it working and make it hopefully easier.

**Comment by WeAreJigital** [comment]
@Shazwazza i have not forgotten just had no time :(
