### ISSUE TITLE
Exception in ConvertValues

### ISSUE THREAD

**Issue by pariashiri1984** [SDKits/ExamineX#85]
I am using a licenced version 4.0.0 and Umbraco version 10.2.1. I am using ExamineX for searching through particular nodes. All is okay in the free version locally but it's not working on licenced as I can't see this error locally I can't fix it. At first, I added some new Custom field types but due to this error I removed them guessing that was the source of the issue but after removing still same error happening, Any idea?
I have this error in the Umbraco log:

System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at ExamineX.AzureSearch.AzureSearchFieldValueType.ConvertValues(IEnumerable`1 values, SearchField field)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at ExamineX.AzureSearch.AzureSearchFieldValueType.AddValues(ExamineDocument doc, SearchField field, IReadOnlyList`1 values)
   at ExamineX.AzureSearch.AzureSearchIndex.A(IReadOnlyList`1 )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at ExamineX.AzureSearch.AzureSearchIndex.A(IEnumerable`1 , CancellationToken )
   at ExamineX.AzureSearch.AzureSearchIndex.E.A(Task )

**Comment by Shazwazza** [comment]
Hi there,

thanks for the report.

This will occur, for example, if you have a field defined as long and an invalid value is passed for it. This would also include an empty string. 

A fix will be released shortly with version 4.1.4. A warning will be logged when this will occur and the value for the field will be set as the default value for that value type.

**Comment by Shazwazza** [comment]
4.1.4 has been released.
